### ISSUE TITLE
bcbio.variation.recall ensemble fails to find reference dictionary

### ISSUE THREAD

**Issue by stsmall** [chapmanb/bcbio.variation.recall#10]
Hi Brad,
When I ran bcbio.variation.recall ensemble it seems to complain about a reference dictionary. I did construct a reference dictionary with the same basename (Wb-PNG_Genome_assembly-pt22.spades.ragoutrep.gapfill.mt) that is named Wb-PNG_Genome_assembly-pt22.spades.ragoutrep.gapfill.mt.dict. I ran GATK HaplotypeCaller using this dict so it should be properly formed. Any ideas?. Also Java version 1.7.0_60, maybe that is the issue.

thanks,
scott

Error:
~/programs_that_work/bcbio.variation.recall/bin/bcbio-variation-recall ensemble test.ensemble_recall.vcf /SerreDLab/smalls/bowtie2_index/Wb-PNG_Genome_assembly-pt22.spades.ragoutrep.gapfill.mt.fasta PNG0018-1.fb-2.vcf PNG0018-1.HC-2.vcf

2016-Apr-24 14:50:23 -0400 tequila ERROR [bcbio.variation.recall.main] -
java.lang.IllegalArgumentException: A reference dictionary is required for creating Tribble indices on the fly
htsjdk.variant.variantcontext.writer.VariantContextWriterBuilder.build  VariantContextWriterBuilder.java:  389
                          sun.reflect.NativeMethodAccessorImpl.invoke0                                  :
                           sun.reflect.NativeMethodAccessorImpl.invoke                                  :
                       sun.reflect.DelegatingMethodAccessorImpl.invoke                                  :
                                       java.lang.reflect.Method.invoke                                  :
                           clojure.lang.Reflector.invokeMatchingMethod                    Reflector.java:   93
                      clojure.lang.Reflector.invokeNoArgInstanceMember                    Reflector.java:  313
   bcbio.variation.variantcontext/write-vcf-w-template/make-vcf-writer                variantcontext.clj:  173
                                                   clojure.core/map/fn                          core.clj: 2624
                                             clojure.lang.LazySeq.sval                      LazySeq.java:   40
                                              clojure.lang.LazySeq.seq                      LazySeq.java:   49
                                                   clojure.lang.RT.seq                           RT.java:  507
                                                      clojure.core/seq                          core.clj:  137
                                                   clojure.core/zipmap                          core.clj: 2947
                   bcbio.variation.variantcontext/write-vcf-w-template                variantcontext.clj:  183
                                            clojure.lang.RestFn.invoke                       RestFn.java:  573
                   bcbio.variation.ensemble.intersect/ensemble-vcfs/fn                     intersect.clj:   87
                      bcbio.variation.ensemble.intersect/ensemble-vcfs                     intersect.clj:   85
                              bcbio.variation.ensemble.intersect/-main                     intersect.clj:  139
                                           clojure.lang.RestFn.applyTo                       RestFn.java:  137
                                                    clojure.core/apply                          core.clj:  630
                                     bcbio.variation.recall.main/-main                          main.clj:   33
                                           clojure.lang.RestFn.applyTo                       RestFn.java:  137
                                      bcbio.variation.recall.main.main                                  :

**Comment by chapmanb** [comment]
Scott;
Thanks much for the report and sorry about the issue. The ensemble method wasn't correctly handling non-bgzipped output files, causing GATK to issue this error during writing. I pushed a fix in 0.1.6:

https://github.com/chapmanb/bcbio.variation.recall/releases/download/v0.1.6/bcbio-variation-recall

which will automatically bgzip outputs and allows the GATK-based output VCF file writing to complete correctly. You should be able to get this version and re-run in place. Hopefully this'll get your ensemble preparation finished cleanly.
