### ISSUE TITLE
merge vcf

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio.variation.recall#11]
Hi Brad,

I see that you are in the process of making it available to users to do merge calls, squaring calls and ensemble calling. Is this code available to users. We are in the process of merging calls from same sample set run in different batches and also merge files from independent callers. I know we can do this as part of bcbio package. What we all have to start with is a vcf file, so I am looking if you guys have something and I found this page. Can you please let me know if I will be able to use your code for generating the merged calls?

Thanks,

Diya

**Comment by chapmanb** [comment]
Diya;
Absolutely, releases are available here:

https://github.com/chapmanb/bcbio.variation.recall/releases

`bcbio-variation-recall`is also installed as part of bcbio with all the dependencies. Usage is documented here:

https://github.com/chapmanb/bcbio.variation.recall#usage

Hope this helps.

**Comment by DiyaVaka** [comment]
Hi Brad,

I did try that. Its installed in the bin directory inside the bcbio directory. When I used the usage as described it says it requires java. So I used java -jar /mnt/speed/qc/sequencing/bcbio/bin/bcbio-variation-recall merge GRCh37.fa 1011.vcf 1014.vcf 1020.vcf

and it throws an error saying


[sequencing@ihg-headnode-1 ~]$ /home/sequencing/src/jdk1.7.0_25/bin/java -jar /mnt/speed/qc/sequencing/bcbio/bin/bcbio-variation-recall  merge /mnt/speed/qc/sequencing/biodata/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa /coldstorage/19_project/19_vcf/n201-1011_93genes.vcf /coldstorage/U19_project/U19_vcf/n201-1014_93g.vcf

2016-07-12 19:25:50 ihg-headnode-1 INFO [bcbio.run.itx] - /mnt/speed/qc/sequencing/biodata/genomes/Hsapiens/GRCh37/bwa/inprep/txtmp1171372363155258205/run.sh: line 2: bgzip: command not found

2016-07-12 19:25:50 ihg-headnode-1 INFO [bcbio.run.itx] - view: invalid option -- 'f'

2016-07-12 19:25:50 ihg-headnode-1 INFO [bcbio.run.itx] - open: No such file or directory

2016-07-12 19:25:50 ihg-headnode-1 ERROR [bcbio.run.itx] -

java.lang.Exception: Shell command failed: bcftools view -f 'PASS,.' /coldstorage/19_project/19_vcf/n201-1014_93g.vcf | bgzip -c > /mnt/speed/qc/sequencing/biodata/genomes/Hsapiens/GRCh37/bwa/inprep/txtmp1171372363155258205/n201-1014_93g-qprep-passonly.vcf.gz

                     open: No such file or directory

                     view: invalid option -- 'f'

                     /mnt/speed/qc/sequencing/biodata/genomes/Hsapiens/GRCh37/bwa/inprep/txtmp1171372363155258205/run.sh: line 2: bgzip: command not found

                         bcbio.run.itx/check-run       itx.clj:  168

bcbio.variation.ensemble.prep/bgzip-index-vcf/fn      prep.clj:   47

   bcbio.variation.ensemble.prep/bgzip-index-vcf      prep.clj:   47

                      clojure.lang.RestFn.invoke   RestFn.java:  559

  bcbio.variation.recall.merge/prep-by-region/fn     merge.clj:  135

                             clojure.core/map/fn      core.clj: 2622

                       clojure.lang.LazySeq.sval  LazySeq.java:   40

                        clojure.lang.LazySeq.seq  LazySeq.java:   49

                             clojure.lang.RT.seq       RT.java:  507

                                clojure.core/seq      core.clj:  137

                             clojure.core/map/fn      core.clj: 2616

                       clojure.lang.LazySeq.sval  LazySeq.java:   40

                        clojure.lang.LazySeq.seq  LazySeq.java:   49

                             clojure.lang.RT.seq       RT.java:  507

                                clojure.core/seq      core.clj:  137

                              clojure.core/apply      core.clj:  630

                             clojure.core/mapcat      core.clj: 2660

                      clojure.lang.RestFn.invoke   RestFn.java:  423

  bcbio.variation.recall.split/group-breakpoints     split.clj:   67

     bcbio.variation.recall.split/group-pregions     split.clj:   87

     bcbio.variation.recall.merge/prep-by-region     merge.clj:  138

       bcbio.variation.recall.merge/combine-vcfs     merge.clj:  152

              bcbio.variation.recall.merge/-main     merge.clj:  193

                     clojure.lang.RestFn.applyTo   RestFn.java:  137

                              clojure.core/apply      core.clj:  630

            bcbio.variation.recall.main/-main/fn      main.clj:   34

               bcbio.variation.recall.main/-main      main.clj:   33

                     clojure.lang.RestFn.applyTo   RestFn.java:  137

                bcbio.variation.recall.main.main              :


2016-07-12 19:25:50 ihg-headnode-1 ERROR [bcbio.variation.recall.main] -

java.lang.Exception: Shell command failed: bcftools view -f 'PASS,.' /coldstorage/19_project/19_vcf/n201-1014_93g.vcf | bgzip -c > /mnt/speed/qc/sequencing/biodata/genomes/Hsapiens/GRCh37/bwa/inprep/txtmp1171372363155258205/n201-1014_93g-qprep-passonly.vcf.gz

                     open: No such file or directory

                     view: invalid option -- 'f'

                     /mnt/speed/qc/sequencing/biodata/genomes/Hsapiens/GRCh37/bwa/inprep/txtmp1171372363155258205/run.sh: line 2: bgzip: command not found

                         bcbio.run.itx/check-run       itx.clj:  168

bcbio.variation.ensemble.prep/bgzip-index-vcf/fn      prep.clj:   47

   bcbio.variation.ensemble.prep/bgzip-index-vcf      prep.clj:   47

                      clojure.lang.RestFn.invoke   RestFn.java:  559

  bcbio.variation.recall.merge/prep-by-region/fn     merge.clj:  135

                             clojure.core/map/fn      core.clj: 2622

                       clojure.lang.LazySeq.sval  LazySeq.java:   40

                        clojure.lang.LazySeq.seq  LazySeq.java:   49

                             clojure.lang.RT.seq       RT.java:  507

                                clojure.core/seq      core.clj:  137

                             clojure.core/map/fn      core.clj: 2616

                       clojure.lang.LazySeq.sval  LazySeq.java:   40

                        clojure.lang.LazySeq.seq  LazySeq.java:   49

                             clojure.lang.RT.seq       RT.java:  507

                                clojure.core/seq      core.clj:  137

                              clojure.core/apply      core.clj:  630

                             clojure.core/mapcat      core.clj: 2660

                      clojure.lang.RestFn.invoke   RestFn.java:  423

  bcbio.variation.recall.split/group-breakpoints     split.clj:   67

     bcbio.variation.recall.split/group-pregions     split.clj:   87

     bcbio.variation.recall.merge/prep-by-region     merge.clj:  138

       bcbio.variation.recall.merge/combine-vcfs     merge.clj:  152

              bcbio.variation.recall.merge/-main     merge.clj:  193

                     clojure.lang.RestFn.applyTo   RestFn.java:  137

                              clojure.core/apply      core.clj:  630

            bcbio.variation.recall.main/-main/fn      main.clj:   34

               bcbio.variation.recall.main/-main      main.clj:   33

                     clojure.lang.RestFn.applyTo   RestFn.java:  137


Thanks,


Diya Vaka

Bioinformatics Programmer Analyst

Institute of Human Genetics

513 Parnassus Ave., HSE S966

San Franscisco, CA 94143

W 415-502-3570

dedeepya.vaka@ucsf.edu


________________________________

**Comment by DiyaVaka** [comment]
figured it out. Thanks a bunch
