### ISSUE TITLE
merge vcf

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio.variation.recall#12]
Hi Brad,

Attached is the script I am using and the error it says is below. Also I attached the vcf file which it is complaining
[n201-1017_test.vcf.txt](https://github.com/chapmanb/bcbio.variation.recall/files/362286/n201-1017_test.vcf.txt)
[bcbiomerge.sh.txt](https://github.com/chapmanb/bcbio.variation.recall/files/362288/bcbiomerge.sh.txt)

 about.

2016-07-13 12:20:03 ihg-headnode-1 INFO [bcbio.run.itx] - [E::vcf_hdr_read] no sample line
2016-07-13 12:20:03 ihg-headnode-1 INFO [bcbio.run.itx] - Failed to open /coldstorage/U19_project/U19_vcf/n201-1017_93g.vcf: could not parse header
2016-07-13 12:20:03 ihg-headnode-1 ERROR [bcbio.run.itx] - 
java.lang.Exception: Shell command failed: bcftools view -f 'PASS,.' /coldstorage/U19_project/U19_vcf/n201-1017_93g.vcf | bgzip -c > /coldstorage/U19_project/U19_vcf/results_UG/inprep/txtmp1500156387816019744/n201-1017_93g-qprep-passonly.vcf.gz
                     Failed to open /coldstorage/U19_project/U19_vcf/n201-1017_93g.vcf: could not parse header
                     [E::vcf_hdr_read] no sample line
                         bcbio.run.itx/check-run       itx.clj:  168
bcbio.variation.ensemble.prep/bgzip-index-vcf/fn      prep.clj:   47
   bcbio.variation.ensemble.prep/bgzip-index-vcf      prep.clj:   47
                      clojure.lang.RestFn.invoke   RestFn.java:  559
  bcbio.variation.recall.merge/prep-by-region/fn     merge.clj:  135
                             clojure.core/map/fn      core.clj: 2622
                       clojure.lang.LazySeq.sval  LazySeq.java:   40
                        clojure.lang.LazySeq.seq  LazySeq.java:   49
                             clojure.lang.RT.seq       RT.java:  507
                                clojure.core/seq      core.clj:  137
                             clojure.core/map/fn      core.clj: 2616
                       clojure.lang.LazySeq.sval  LazySeq.java:   40
                        clojure.lang.LazySeq.seq  LazySeq.java:   49
                             clojure.lang.RT.seq       RT.java:  507
                                clojure.core/seq      core.clj:  137
                              clojure.core/apply      core.clj:  630
                             clojure.core/mapcat      core.clj: 2660
                      clojure.lang.RestFn.invoke   RestFn.java:  423
  bcbio.variation.recall.split/group-breakpoints     split.clj:   67
     bcbio.variation.recall.split/group-pregions     split.clj:   87
     bcbio.variation.recall.merge/prep-by-region     merge.clj:  138
       bcbio.variation.recall.merge/combine-vcfs     merge.clj:  152
              bcbio.variation.recall.merge/-main     merge.clj:  193
                     clojure.lang.RestFn.applyTo   RestFn.java:  137
                              clojure.core/apply      core.clj:  630
            bcbio.variation.recall.main/-main/fn      main.clj:   34
               bcbio.variation.recall.main/-main      main.clj:   33
                     clojure.lang.RestFn.applyTo   RestFn.java:  137
                bcbio.variation.recall.main.main              :     

2016-07-13 12:20:03 ihg-headnode-1 ERROR [bcbio.variation.recall.main] - 
java.lang.Exception: Shell command failed: bcftools view -f 'PASS,.' /coldstorage/U19_project/U19_vcf/n201-1017_93g.vcf | bgzip -c > /coldstorage/U19_project/U19_vcf/results_UG/inprep/txtmp1500156387816019744/n201-1017_93g-qprep-passonly.vcf.gz
                     Failed to open /coldstorage/U19_project/U19_vcf/n201-1017_93g.vcf: could not parse header
                     [E::vcf_hdr_read] no sample line
                         bcbio.run.itx/check-run       itx.clj:  168
bcbio.variation.ensemble.prep/bgzip-index-vcf/fn      prep.clj:   47
   bcbio.variation.ensemble.prep/bgzip-index-vcf      prep.clj:   47
                      clojure.lang.RestFn.invoke   RestFn.java:  559
  bcbio.variation.recall.merge/prep-by-region/fn     merge.clj:  135
                             clojure.core/map/fn      core.clj: 2622
                       clojure.lang.LazySeq.sval  LazySeq.java:   40
                        clojure.lang.LazySeq.seq  LazySeq.java:   49
                             clojure.lang.RT.seq       RT.java:  507
                                clojure.core/seq      core.clj:  137
                             clojure.core/map/fn      core.clj: 2616
                       clojure.lang.LazySeq.sval  LazySeq.java:   40
                        clojure.lang.LazySeq.seq  LazySeq.java:   49
                             clojure.lang.RT.seq       RT.java:  507
                                clojure.core/seq      core.clj:  137
                              clojure.core/apply      core.clj:  630
                             clojure.core/mapcat      core.clj: 2660
                      clojure.lang.RestFn.invoke   RestFn.java:  423
  bcbio.variation.recall.split/group-breakpoints     split.clj:   67
     bcbio.variation.recall.split/group-pregions     split.clj:   87
     bcbio.variation.recall.merge/prep-by-region     merge.clj:  138
       bcbio.variation.recall.merge/combine-vcfs     merge.clj:  152
              bcbio.variation.recall.merge/-main     merge.clj:  193
                     clojure.lang.RestFn.applyTo   RestFn.java:  137
                              clojure.core/apply      core.clj:  630
            bcbio.variation.recall.main/-main/fn      main.clj:   34
               bcbio.variation.recall.main/-main      main.clj:   33
                     clojure.lang.RestFn.applyTo   RestFn.java:  137
                bcbio.variation.recall.main.main              :     

Stop Date       = Wed Jul 13 12:20:03 PDT 2016

**Comment by chapmanb** [comment]
Diya;
bcftools is complaining that your input file is invalid. I'm not sure if the file you attached was corrupted via transfer to GitHub, but it is currently not a valid VCF file. It has quotes around many of the header lines and lots of blank lines between headers. If the original file is clean and this is a transfer issue you could post as a gist (https://gist.github.com/) and we could try to sort out the problem. Hope this helps.

**Comment by DiyaVaka** [comment]
Thank you Brad. Looks like the client sent us a corrupted file. I will recheck with them. Also what happen when the same sample is present across multiple vcfs file and I try to merge all these into one big vcf. Does the program needs to have only unique samples?

**Comment by chapmanb** [comment]
Thanks for confirming the problem. It does need unique samples to merge and should give an error if you have duplicate samples. Hope this helps.

**Comment by DiyaVaka** [comment]
hi Brad,

The program throws an error saying incompatible headers. Attached is the stdout file
[merge.936340.stdout.txt](https://github.com/chapmanb/bcbio.variation.recall/files/362690/merge.936340.stdout.txt)

**Comment by DiyaVaka** [comment]
Also Brad when the run is complete I get a vcf file for each chromosome. Does the program not spit one with all the chromosomes in it?

Thanks,

**Comment by chapmanb** [comment]
Diya;
Sorry about the header problems. This merge code is not fancy and requires you to have valid headers -- it won't try to fix or massage problems that the underlying GATK and bcftools programs can't handle. The only way to fix this is to pre-adjust your headers so `ESPAF` is consistent between the files. Sorry to not have a cleaner solution.

The output should be a single merged file in the out-file you specified on the command line. It does split into sections for parallel merging but should provide a full file at the end. Is it possible that it did not finish cleanly for some reason?

Hope this helps.

**Comment by DiyaVaka** [comment]
Thank you Brad. I am running with numpass=1 and it gives me a java heap space error. How should I be running this with java increased memory

bcbio-variation-recall ensemble numpass= 1 --names gatk, platypus, gatk-haplotype output.vcf $input1.vcf, $input2.vcf, $input3.vcf

Thanks,

**Comment by chapmanb** [comment]
Diya;
`bcbio-variation-recall` handles standard java memory specifications so you can adjust with something like:
```
-Xms1g -Xmx4g
```
Hope this helps

**Comment by DiyaVaka** [comment]
Hi brad,

I changed the default_jvm_args to the one you mentioned above. When I execute the file it says Invalid or corrupt jar file. Am I doing it in the wrong place. Even though I revert it back to the old setting it still gives the same error

**Comment by chapmanb** [comment]
Sorry for the confusion. You add those commands on the command line:
```
bcbio-variation-recall -Xms1g -Xmx4g ensemble numpass= 1 --names gatk, platypus, gatk-haplotype output.vcf $input1.vcf, $input2.vcf, $input3.vcf
```
not by editing the script. That's binary script with the jar embedded so it sounds like the editing process corrupted it. If you re-install and run with them on the command line hopefully it will work for you.

**Comment by DiyaVaka** [comment]
Thank you Brad. Now its giving an "Exception in thread "main" java.lang.OutOfMemeoryError: GC overhead limit exceeded..

I tried to change -Xmx to 10g but of no use. When I read forums they say that lot of stuff is getting written to garbage collection. Did you encounter this issue before?

Thanks,

**Comment by chapmanb** [comment]
I haven't seen that but we also use:
```
-XX:+UseSerialGC
```
in bcbio which can help with GC issues on same Java versions. Hope adding that to the commandline resolves it for you.
