### ISSUE TITLE
ensemble error latest

### ISSUE THREAD

**Issue by ubaid1101** [chapmanb/bcbio.variation.recall#18]
Hi, I am getting this error while running ensemble. Any insight?

bcbio.variation.recall/bin/bcbio-variation-recall ensemble --names -n 1 output.vcf.gz hg19.fa sorted_novosort.vcf.gz sorted_picard.vcf.gz sorted_samblaster.vcf.gz

ERROR [bcbio.variation.recall.main] - java.lang.IndexOutOfBoundsException: 
             clojure.lang.PersistentVector.arrayFor  PersistentVector.java:  153
                  clojure.lang.PersistentVector.nth  PersistentVector.java:  157
                                clojure.lang.RT.nth                RT.java:  839
                                   clojure.core/nth               core.clj:  862
                            clojure.core/partial/fn               core.clj: 2493
                                clojure.core/map/fn               core.clj: 2624
                          clojure.lang.LazySeq.sval           LazySeq.java:   40
                           clojure.lang.LazySeq.seq           LazySeq.java:   49
                             clojure.lang.Cons.next              Cons.java:   39
                          clojure.lang.LazySeq.next           LazySeq.java:   81
                               clojure.lang.RT.next                RT.java:  674
                                  clojure.core/next               core.clj:   64
                                clojure.string/join             string.clj:  186
  bcbio.variation.ensemble.intersect/ann-vc-w-names          intersect.clj:   42
   bcbio.variation.ensemble.intersect/get-rep-vc/fn          intersect.clj:   57
                               clojure.core/comp/fn               core.clj: 2438
                                clojure.core/map/fn               core.clj: 2624
                          clojure.lang.LazySeq.sval           LazySeq.java:   40
                           clojure.lang.LazySeq.seq           LazySeq.java:   49
                                clojure.lang.RT.seq                RT.java:  507
                                   clojure.core/seq               core.clj:  137
                                clojure.core/map/fn               core.clj: 2616
                          clojure.lang.LazySeq.sval           LazySeq.java:   40
                           clojure.lang.LazySeq.seq           LazySeq.java:   49
                                clojure.lang.RT.seq                RT.java:  507
                                   clojure.core/seq               core.clj:  137
bcbio.variation.variantcontext/write-vcf-w-template     variantcontext.clj:  189
                         clojure.lang.RestFn.invoke            RestFn.java:  573
bcbio.variation.ensemble.intersect/ensemble-vcfs/fn          intersect.clj:   88
   bcbio.variation.ensemble.intersect/ensemble-vcfs          intersect.clj:   86
           bcbio.variation.ensemble.intersect/-main          intersect.clj:  140
                        clojure.lang.RestFn.applyTo            RestFn.java:  137
                                 clojure.core/apply               core.clj:  630
               bcbio.variation.recall.main/-main/fn               main.clj:   34
                  bcbio.variation.recall.main/-main               main.clj:   33
                        clojure.lang.RestFn.applyTo            RestFn.java:  137
                   bcbio.variation.recall.main.main                       :

**Comment by chapmanb** [comment]
Sorry about the unhelpful error message. The problem is that it expects the `--names` input to be a comma separated list equal to the number of input VCFs. So something like
```
bcbio.variation.recall/bin/bcbio-variation-recall ensemble --names novosort,picard,samblaster -n 1 output.vcf.gz hg19.fa sorted_novosort.vcf.gz sorted_picard.vcf.gz sorted_samblaster.vcf.gz
```
should hopefully work correctly for you. Please let us know if you run into any other issues.

**Comment by ubaid1101** [comment]
Thanks for your prompt response. It seems to be working this way. Aprrieate your support.
