### ISSUE TITLE
"Warning(freebayes): Could not set the region of the variants input file to ..."

### ISSUE THREAD

**Issue by svm-zhang** [chapmanb/bcbio.variation.recall#4]
Hi Brad,

Thanks for sharing this toolkit.

I have a population of about 100 individuals. I used freebayes to get a call set for each individual. To give a test run, I used the "merge" subprogram on two indvidual VCFs. I then feed the resulting "merged.vcf" to the "square" subprogram to recall using freebayes. The following was my command line:

bcbio-variation-recall square -m freebayes merge.join.vcf ref.fa merge.vcf ind1.bam ind2.bam

Then I got this warning:

"Warning(freebayes): Could not set the region of the variants input file to ..."

This warning seems coming from freebayes. Should I worry about this warning? Did I do something wrong with my command line?

I also tried:

bcbio-variation-recall square -m freebayes merge.join.vcf ref.fa ind1.vcf ind2.vcf ind1.bam ind2.bam

And the warning showed up as well.

Appreciate any help! Thanks!

Simo

**Comment by chapmanb** [comment]
Simo;
That's an expected warning from FreeBayes, so not anything at all to worry about. If you got a `merge.join.vcf` file that looks good everything should be all good. Thanks for using bcbio.variation.recall and hope the squared file looks at expected.
