### ISSUE TITLE
What steps does bcbio-variation-recall merge actually do?

### ISSUE THREAD

**Issue by inti** [chapmanb/bcbio.variation.recall#6]
Hi,
What does bcbio-variation-recall merge actually do? 
does it do a simple merge or does it do normalisation and left align as well? 

Cheers,
Inti

**Comment by chapmanb** [comment]
Inti;
It does a merge using GATK's CombineVariants:

https://github.com/chapmanb/bcbio.variation.recall/blob/master/src/bcbio/variation/recall/merge.clj#L58

It doesn't run normalization of left alignment -- those are all things we take care of inside of bcbio during the calling process. Hope this helps

**Comment by inti** [comment]
Yes it does, cheers. 
Inti
