### ISSUE TITLE
How should vcfs/bams be specified in a text file/command line

### ISSUE THREAD

**Issue by danhalligan** [chapmanb/bcbio.variation.recall#7]
In what order should vcfs / bams be specified on the command line or in a text file so that the vcfs are properly associated with their associated bam files?

For example, if sample 1 has files: sample1.vcf, sample1-final.bam and sample 2 has: sample2.vcf, sample2-final.bam, how should the command to bcbio-variation-recall be specified? I'm guessing it should be:

    bcbcio-variation-recall square out.vcf ref.fa sample1.vcf sample2.vcf sample1-final.bam sample2-final.bam

In which case, are associations determined by the order in which the vcfs and bam files appear on the command line?

Thanks!

**Comment by chapmanb** [comment]
Dan;
It matches VCF samples to BAM files based on sample names in the VCF and read groups in the BAM file. There is no order requirement in the input file, and this lets you use multisample input VCF files. I added a note to the documentation as well to make this more clear. Hope this helps.

**Comment by danhalligan** [comment]
Got it - thanks!
